services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./handlers:/etc/caddy/handlers
      - chs_shared:/etc/chs:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - dns_network

  chs_server:
    image: traumaer/chs-server:latest
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - chs_shared:/data/chs/shared
      - chs_private:/data/chs/private
    env_file:
      - .env
    networks:
      - dns_network

  coredns:
    image: coredns/coredns:1.12.1
    restart: unless-stopped
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
      - ./coredns/internal.domain.db:/etc/coredns/internal.domain.db
      - ./coredns/hosts.blocklist:/etc/coredns/hosts.blocklist
    command: -conf /etc/coredns/Corefile
    env_file:
      - .env
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns_network

volumes:
  chs_shared:
  chs_private:
  caddy_data:
  caddy_config:

networks:
  dns_network: