services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dns_network

  coredns:
    image: coredns/coredns:1.12.1
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
      - ./coredns/internal.domain.db:/etc/coredns/internal.domain.db
      - ./coredns/hosts.blocklist:/etc/coredns/hosts.blocklist
    command: -conf /etc/coredns/Corefile
    depends_on:
      - unbound
    env_file:
      - .env
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    networks:
      - dns_network


  unbound:
    image: klutchell/unbound
    volumes:
      - ./unbound/custom.conf.d:/etc/unbound/custom.conf.d
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: 172.20.0.2 # gives unbound a static ip address within the docker network for use in our Corefile

volumes:
  caddy_data:
  caddy_config:

networks:
  dns_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16