services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./handlers:/etc/caddy/handlers
      - chs_shared:/etc/chs:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - unbound
    networks:
      - dns_network

  chs_server:
    image: traumaer/chs-server:latest
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - chs_shared:/data/chs/shared
      - chs_private:/data/chs/private
    env_file:
      - .env
    depends_on:
      - unbound
    networks:
      - dns_network

  coredns:
    image: coredns/coredns:1.12.1
    restart: unless-stopped
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
      - ./coredns/internal.domain.db:/etc/coredns/internal.domain.db
      - ./coredns/hosts.blocklist:/etc/coredns/hosts.blocklist
    command: -conf /etc/coredns/Corefile
    depends_on:
      - unbound
    env_file:
      - .env
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns_network

  unbound:
    image: klutchell/unbound
    restart: unless-stopped
    volumes:
      - ./unbound/custom.conf.d:/etc/unbound/custom.conf.d
    networks:
      dns_network:
        ipv4_address: 172.20.0.2 # gives unbound a static ip address within the docker network for use in our Corefile

volumes:
  chs_shared:
  chs_private:
  caddy_data:
  caddy_config:

networks:
  dns_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16